language: node_js
node_js:
  - "10"
cache: yarn

install: yarn install --frozen-lockfile
script:
  - echo "Not found tests"

jobs:
  include:
    - stage: deploy
      script:
        - yarn bootstrap
        - yarn build
        - npx netlify-cli deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_ACCESS_TOKEN --dir=./build --prod
      on:
        branch: master
    - stage: docker-deploy
      env:
        - IMAGE_NAME=andrelmlins1/revelt
      script:
        - yarn bootstrap
        - yarn build
        - docker build --pull --cache-from "${IMAGE_NAME}:latest" --tag "$IMAGE_NAME" .
        - docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"
        - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"
      on:
        branch: master
      deploy:
        provider: script
        script: docker push "${IMAGE_NAME}:latest"
        on:
          branch: master
